[build]
  command = "npm ci && npm run build"
  publish = "dist/prayer-share/browser"
  framework = "#static"   # <- forces static; skips angular runtime

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
